name: Udemy data scraper
on:
  workflow_dispatch:
    inputs:
      output_name:
        description: "Result output filename"
        required: true
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.MY_PAT }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install pip requirements.txt
        run: pip install -r requirements.txt

      - name: Run Python
        run: |
          export SCRAPE_OUTPUT=${{ github.event.inputs.output_name }}
          xvfb-run python src/access_api.py

      - name: Save result
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github"
          git add .
          git commit -m "Save details to github"
          git push
